# Change these first
owner: sorbay # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
assignees:
  - funkluk
sites:
  - name: Website
    url: https://www.sorbay.com
    icon: https://sorbay.com/favicon-32x32.png
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/sorbay/status/master/assets/sorbay-logo.png
  themeUrl: https://raw.githubusercontent.com/sorbay/status/master/assets/sorbay-theme.css
  favicon: https://raw.githubusercontent.com/sorbay/status/master/assets/favicon-32x32.png
  name: ""
  introTitle: "the key to global cloud security"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
